### ISSUE TITLE
New Installation of Plugin fails

### ISSUE THREAD

**Issue by chfsx** [ilifau/assStackQuestion#89]
There are at least two errors while installing the plugin in ILIAS 6:
- there's a comma too much in "classes/stack/cas/casstring.units.class.php" in Line 184, should be `$maximalocal .= '    stack_unit_si_prefix_tex:[' . implode(', ', $tex) . "],\n";` instead of `$maximalocal .= '    stack_unit_si_prefix_tex:[' . implode(', ', $tex,) . "],\n";`
- I get a `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'options_matrix_parents' for key 'PRIMARY'` while installing the DB.

**Comment by jcopado** [comment]
The extra comma in casstring.units.class.php was solved in a bugfix last November (https://github.com/ilifau/assStackQuestion/commit/cbbe113a85c43d5decad2f544f62f4e3f838cd63). Please, ensure you are pulling the branch master-ilias6 and not a different one for your ILIAS 6 installation.

Regarding the other error, I will release a bugfix Version that should solve that issue this week, my question is, was the STACK Plugin already installed in the platform, or is a fres new ILIAS6 installation?

**Comment by chfsx** [comment]
Hi @jcopado thanks for the quick reply!
I was on 0fdf1a63b1ff05590cabe9f628966f9011a5656a and forgot to pull, this has been fixed as you mentioned.

Yes, I pretty sure the plugin was installed once but then removed

**Comment by jcopado** [comment]
The Integrity Constraint Violation error should no longer occur in new bugfix Version 3.3.3 for ILIAS 6.

**Comment by chfsx** [comment]
Hi @jcopado 

I hope I have the moste recent version now, but I think this doesn't work like this (and I still get the error):
```php
    if (!$db->tableColumnExists("xqcas_configuration", "options_matrix_parents")) {
        $db->insert("xqcas_configuration", array('parameter_name' => array('text', "options_matrix_parents"), 'value' => array('clob', '['), 'group_name' => array('text', 'options')));
    }
```
tries to insert a a new entry in the table 'xqcas_configuration' if the table-column 'options_matrix_parents' does not exist (which is always the case. There is an entry in the table with parameter_name=options_matrix_parents)

I suggest to remove all the `if (!$db->tableColumnExists("xqcas_configuration", ...` statement in at least steps 35, 37 and 38 again since they do not what you expect. 

It should be something like (pseudocode):
```
if( entry_in_db_xy_in_colum_parameter_name_with_value_YZ does not exist ) {
   insert entry_in_db_xy_in_colum_parameter_name_with with value YZ
}
```

**Comment by jcopado** [comment]
You are totally right, I will release a new bugfix Version tomorrow.
Thank you.

**Comment by jcopado** [comment]
Version 3.3.4 has been released.
Please, let me know if this solves your problems while re-installing the plugin.

**Comment by chfsx** [comment]
Thanks a lot, re-installing the plugin now worked!
